baseURL = "http://blog.yukiisbo.red/"
languageCode = "en-us"
title = "blog.yukiisbo.red"

theme = "yuki"

paginate = 3
paginatePath = "page"

pygmentsCodefences = true
pygmentsUseClasses = true

[permalinks]
  posts = "/posts/:year/:month/:title"
